# Generated by Django 4.2.3 on 2023-07-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="student_id",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
