# Generated by Django 4.1.1 on 2023-08-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_profile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(default='N', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Not Specified')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobby',
            field=models.CharField(default='N', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(default='N', max_length=200, null=True),
        ),
    ]
