# Generated by Django 4.2.3 on 2023-08-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_profile_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bsc",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="clubs",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="college",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="courses",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="facinitial",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="gsuiteEmail",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="msc",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phd",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="projects",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="publication",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="school",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="university",
            field=models.CharField(
                blank=True, default="BRAC University", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="current_city",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="department",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="hobby",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(
                blank=True, default="None", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profession",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="research_interest",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True, default="Student", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="room_no",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="student_id",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
    ]
