# Generated by Django 4.2.3 on 2023-08-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_profile_bsc_profile_clubs_profile_college_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
    ]
