# Generated by Django 4.2.3 on 2023-08-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="certifications",
            field=models.CharField(blank=True, default="N", max_length=400, null=True),
        ),
    ]
