# Generated by Django 4.2.3 on 2023-08-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_profile_certifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="travel_route",
            field=models.CharField(blank=True, default="N", max_length=400, null=True),
        ),
    ]
