# Generated by Django 4.2.3 on 2023-08-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_profile_travel_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="travel_route",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Route 1",
                        "Abdullahpur -> House Building -> Azampur -> Airport -> Kawla -> Khilkhet -> Biswa Road -> Shewrah -> BRAC University",
                    ),
                    (
                        "Route 2",
                        "Kallyanpur -> Tolarbag -> Sony-Cinema -> Mirpur-College -> Swimming-Fed -> Popular-diag. -> Pallabi -> Bonolata-shop -> Mirpur-ceramic -> Pallabi-thana -> Kalshi -> ECB -> BRAC University",
                    ),
                    (
                        "Route 3",
                        "Jigatola -> Shankar -> Mohammadpur -> Manik Mia Ave. -> BRAC University",
                    ),
                    (
                        "Route 4",
                        "Azimpur-etim-khana -> Azimpur Chowrasta -> New Market -> Happy Arcade -> Dhanmondi -> Kalabagan Krira -> Sobhanbag -> Manik Mia Ave -> Khejur Bagan -> BRAC University",
                    ),
                    (
                        "Route 5",
                        "Jatrabari -> Doyaganj Mour -> Ittefaq Mour -> Mugda -> Bouddha Mandir -> Bashabo -> Khidmah hospital -> Malibag Railgate -> Abul Hotel -> Rampura TV Center -> BRAC University",
                    ),
                    (
                        "Route 6",
                        "Baldha Garden -> Motijheel -> Arambag -> Fakirapul -> Purana Palton -> Kakrail -> Shantinagar -> Malibag -> Mouchak -> Mogbazar TNT office -> Mogbazar Mour -> BRAC University",
                    ),
                ],
                default="N",
                max_length=400,
                null=True,
            ),
        ),
    ]
