# Generated by Django 4.2.3 on 2023-08-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, default="N", max_length=200, null=True),
        ),
    ]
